### ISSUE TITLE
Harvester crawl doesn't seem to be working?

### ISSUE THREAD

**Issue by andrefigueira** [blacklabelops/logio#5]
Hi there,

Trying to get this setup for work we've got quite a few projects, and the harvester crawl seemed to be perfect, however I can't seem to get it working with more than one numerated log:

See below my docker-composer instance: 

```
  logioweb:
    image: 'quay.io/blacklabelops/logio:latest'
    # container_name: logio
    environment:
      - 'LOGIO_ADMIN_USER='
      - 'LOGIO_ADMIN_PASSWORD='
      - LOGIO_CERTIFICATE_DNAME=
    ports:
      - '28778:28778'
    volumes:
      - '/opt/server'
    networks:
      air:
        ipv4_address: 172.10.0.30

  harvester:
    image: 'quay.io/blacklabelops/logio:latest'
    environment:
      - 'DELAYED_START=10'
      - 'LOGIO_HARVESTER_NODENAME=DockerLogs'
      - 'LOGIO_HARVESTER_STREAMNAME=UnifiedLogs'
      - 'LOGIO_HARVESTER_LOGFILES='
      - 'LOGS_DIRECTORIES=/var/lib/docker'
      - 'LOG_FILE_PATTERN=*.log'
      - 'LOGIO_HARVESTER1STREAMNAME=Phoenix_Reborn'
      - 'LOGIO_HARVESTER1LOGSTREAMS=/var/log/eagleeye/phoenix-reborn/'
      - 'LOGIO_HARVESTER1FILEPATTERN=*.log'
      - 'LOGIO_HARVESTER2STREAMNAME=Medusa'                     # When I remove the second addition the first one now then works, but when i add this second one, I get no nodes show up in log.io
      - 'LOGIO_HARVESTER2LOGSTREAMS=/var/log/eagleeye/medusa/'
      - 'LOGIO_HARVESTER2FILEPATTERN=*.log'
    volumes:
      - '/var/lib/docker:/var/lib/docker'
      - './log/:/var/log/eagleeye/'
```

Any idea what could cause this?

Cheers!
